# Generated by Django 4.2.6 on 2023-10-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
