# Generated by Django 4.2.6 on 2023-10-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_last_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='image',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='associated_images', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='associated_tasks', to='tasks.image'),
        ),
    ]
