# Generated by Django 4.2.6 on 2023-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_image_remove_task_photos_delete_photo_image_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='images', to='tasks.task'),
        ),
    ]
