# Generated by Django 4.2.6 on 2023-10-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_image_image_images_remove_task_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tasks',
        ),
        migrations.AddField(
            model_name='image',
            name='tasks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task'),
        ),
    ]
