# Generated by Django 4.2.6 on 2023-10-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_image_tasks_image_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task'),
        ),
    ]
