# Generated by Django 4.2.6 on 2023-10-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_image_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='TaskImage',
        ),
    ]
