# Generated by Django 4.2.6 on 2023-10-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_image_taskimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='images',
            field=models.ImageField(null=True, upload_to='task_images/'),
        ),
    ]
